src/Entity/Answer.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use App\Repository\AnswerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Carbon\Carbon;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Delete;
use App\Doctrine\SetOwnerListener;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ApiResource(
    //  security: "is_granted('ROLE_USER')",
    operations: [
        new Get(),
        new GetCollection(),
        new Post(
            security: "is_granted('ROLE_USER')",
            securityMessage: "Only authenticated users can create answers"
        ),
        new Put(
            security: "is_granted('ROLE_USER') or object.getOwner() == user",
            securityMessage: "Only authenticated users or owners can update answers"
        ),
        new Delete(
            security: "is_granted('ROLE_USER') and object.getOwner() == user",
            securityMessage: "Only authenticated owners can delete answers"
        ),
    ],
    normalizationContext: ['groups' => ['answer:read'], 'swagger_definition_name' => 'Read'],
    denormalizationContext: ['groups' => ['answer:write'], 'swagger_definition_name' => 'Write'],
)]
#[ApiFilter(PropertyFilter::class)]
#[ApiFilter(OrderFilter::class, properties: ['votes' => 'DESC'])]
#[ApiFilter(SearchFilter::class, properties: ['owner.name' => 'partial'])]
#[ORM\Entity(repositoryClass: AnswerRepository::class)]
#[ORM\EntityListeners([SetOwnerListener::class])]
class Answer
{
    /*public const STATUS_NEED_APPROVAL = 'need_approval';
    public const STATUS_SPAM = 'spam';
    public const STATUS_APPROVED = 'approved';*/

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['answer:read', 'answer:write', 'question:read', 'userAPI:read'])]
    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $content = null;

    #[Groups(['answer:write'])]
    #[ORM\Column]
    private int $votes = 0;

    /*#[Groups(['answer:read', 'answer:write'])]
    #[ORM\Column(length: 15)]
    #[Assert\NotBlank]
    private ?string $status = null;*/

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Gedmo\Timestampable(on: 'create')]
    private $createdAt;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Gedmo\Timestampable(on: 'update')]
    private $updatedAt;

    #[Groups(['answer:read', 'answer:write'])]
    #[ORM\ManyToOne(inversedBy: 'answers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Question $question = null;

    #[Groups(['answer:read'])]
    #[ORM\OneToMany(mappedBy: 'answer', targetEntity: Comment::class)]
    private Collection $comments;

    #[Groups(['answer:read'])]
    #[ORM\ManyToOne(inversedBy: 'answers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    #[Groups(['answer:read'])]
    #[SerializedName('votes')]
    public function getVotesString(): string
    {
        $prefix = $this->votes > 0 ? '+' : '-';

        return sprintf('%s%d', $prefix, abs($this->getVotes()));
    }

    public function upVote(): self
    {
        $this->votes++;

        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;

        return $this;
    }

    /*  public function isApproved(): bool
    {
        return $this->status === self::STATUS_APPROVED;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if (!in_array($status, [self::STATUS_NEED_APPROVAL, self::STATUS_SPAM, self::STATUS_APPROVED])) {
            throw new \InvalidArgumentException('Invalid status "%s"', $status);
        }
        $this->status = $status;

        return $this;
    }*/

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    //#[Groups(['answer:read', 'question:read'])]
    #[Groups(['answer:read'])]
    public function getCreatedAtAgo(): string
    {
        return Carbon::instance($this->getCreatedAt())->diffForHumans();
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    //#[Groups(['answer:read', 'question:read'])]
    #[Groups(['answer:read'])]
    public function getUpdatedAtAgo(): string
    {
        return Carbon::instance($this->getUpdatedAt())->diffForHumans();
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getQuestionText(): string
    {
        if (!$this->getQuestion()) {
            return '';
        }

        return (string)$this->getQuestion()->getQuestion();
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAnswer($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAnswer() === $this) {
                $comment->setAnswer(null);
            }
        }

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Controller/AnswerController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Repository\AnswerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class AnswerController extends AbstractController
{
    #[Route('/answers', name: 'app_answer')]
    public function index(): Response
    {
        return $this->render('answer/index.html.twig', [
            'controller_name' => 'AnswerController',
        ]);
    }

    //commentVote
    #[Route('/answers/{id}/vote', name: 'answer_vote', methods: ['POST'])]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function commentVote(Answer $answer, LoggerInterface $logger, Request $request, EntityManagerInterface $entityManager): Response
    {
        // get user
        $logger->info('{user} is voting on answer {answer}', [
            'user' => $this->getUser()->getUserIdentifier(),
            'answer' => $answer->getId(),
        ]);

        // todo use id to query database for comment
        $data = json_decode($request->getContent(), true);
        $direction = $data['direction'] ?? 'up';

        // use real logic here to save this to the database
        if ($direction === 'up') {
            $logger->info('Voting up!');
            $answer->upVote();
        } else {
            $logger->info('Voting down!');
            $answer->downVote();
        }

        //dd($answer, $request->request->all());

        $entityManager->flush();

        return $this->json(['votes' => $answer->getVotes()]);
    }

    #[Route('/answers/popular', name: 'app_popular_answers', methods: ['GET'])]
    public function popularAnswers(AnswerRepository $answerRepository, Request $request): Response
    {
        $answers = $answerRepository->findeMostPopular(
            $request->query->get('q')
        );

        return $this->render('answer/popularAnswers.html.twig', [
            'answers' => $answers,
        ]);
    }
}

templates/answer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AnswerController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'E:/Privat/Gestaltung/WebEntwicklung/28- Symfony/stackoverflow/src/Controller/AnswerController.php'|file_link(0) }}">src/Controller/AnswerController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'E:/Privat/Gestaltung/WebEntwicklung/28- Symfony/stackoverflow/templates/answer/index.html.twig'|file_link(0) }}">templates/answer/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/answer/popularAnswers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Popular Answers
{% endblock %}

{% block body %}
	<div class="container mx-auto my-10">
		<div class=" d-flex justify-between">
			<h1 class="text-xl">Most Popular Answers</h1>

			<form action="{{ path('app_popular_answers') }}" class="my-5">
				<label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300">Search</label>
				<div class="relative">
					<div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
						<svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
						</svg>
					</div>
					<input type="search" name="q" value="{{ app.request.query.get('q') }}" id="default-search" class="block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search..." required>
					<button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
				</div>
			</form>
		</div>

		<ul class="my-10">
			{% for answer in answers %}
				{{ include('answer/question_answers.html.twig', {
					showQuestion: true,
				}) }}
			{% endfor %}
		</ul>
	</div>
{% endblock %}

templates/answer/question_answers.html.twig
<li>
	{% if showQuestion|default(false) %}
		<a href="{{ path('app_question_show', { slug: answer.question.slug }) }}" class="mb-1 link-secondary">
			<strong>Question:</strong>
			{{ answer.questionText|u.truncate(80, '...') }}
		</a>
	{% endif %}

	<div
		class="flex bg-white shadow-lg rounded-lg md:mx-auto my-5 w-2xl">
		<!--horizantil margin is just for display-->
		<div class="flex items-start px-4 py-6">
			<img class="w-12 h-12 rounded-full object-cover mr-4 shadow" src="{{ answer.owner.getAvatarURL }}" alt="avatar">
			<div class="">
				<div class="flex items-center justify-between">
					<h2 class="text-lg font-semibold text-gray-900 -mt-1">{{ answer.owner.getDisplayName }}
					</h2>
					<small class="text-sm text-gray-700">{{ answer.createdAt|ago }}</small>
				</div>
				<p class="text-gray-700">Joined At
					{{ answer.owner.joinedAt|date('Y-m-d') }}
				</p>
				<p class="mt-3 text-gray-700 text-sm">
					{{ answer.content }}
				</p>
				<div class="mt-4 flex items-center">
					<div class="flex text-gray-700 text-sm mr-3">
						{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
							<div class="vote-arrows" {{ stimulus_controller('answer-vote', { url: path('answer_vote', { id: answer.id } ) }) }}>
								<button class="vote-up btn btn-link" name="direction" value="up" {{ stimulus_action('answer-vote', 'clickVote') }}>
									<i class="far fa-arrow-alt-circle-up"></i>
								</button>
								<button class="vote-down btn btn-link" name="direction" value="down" {{ stimulus_action('answer-vote', 'clickVote') }}>
									<i class="far fa-arrow-alt-circle-down"></i>
								</button>

								<svg fill="none" viewbox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
								</svg>
								<span {{ stimulus_target('answer-vote', 'voteTotal') }}>{{ answer.votes }}</span>
							</div>
						{% endif %}
						{% for  comment in answer.comments %}
							<button class="rounded-2xl border bg-neutral-300 mx-5 px-3 py-1 text-xs font-semibold text-left">
								<span class="font-bold">{{ comment.owner.getDisplayName}}</span><br><span class="font-thin text-center">{{ comment.content }}</span>
							</button>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
</li>