src/Entity/Question.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Doctrine\Orm\Filter\RangeFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\ExistsFilter;
use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Carbon\Carbon;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Delete;
use App\ApiResource\QuestionSearchFilter;
use App\Doctrine\SetOwnerListener;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ApiResource(
    // security: "is_granted('ROLE_USER')",
    operations: [
        new Get(),
        new GetCollection(),
        new Post(
            security: "is_granted('ROLE_USER')",
            securityMessage: "Only authenticated users can create questions"
        ),
        new Put(
            security: "is_granted('ROLE_USER') or object.getOwner() == user",
            securityMessage: "Only authenticated users or owners can update questions"
        ),
        new Delete(
            security: "is_granted('ROLE_USER') and object.getOwner() == user",
            securityMessage: "Only authenticated owners can deletecomments"
        ),
    ],
    normalizationContext: ['groups' => ['question:read'], 'swagger_definition_name' => 'Read'],
    denormalizationContext: ['groups' => ['question:write'], 'swagger_definition_name' => 'Write'],
    paginationClientEnabled: true,
    paginationItemsPerPage: 5,

)]
#[ApiFilter(BooleanFilter::class, properties: ['isPublished'])]
#[ApiFilter(SearchFilter::class, properties: ['title' => 'partial', 'tags.name' => 'exact', 'owner.name' => 'partial'])]
//#[ApiFilter(RangeFilter::class, properties: ['votes'])]
#[ApiFilter(OrderFilter::class, properties: ['votes' => 'DESC'])]
#[ApiFilter(ExistsFilter::class, properties: ['answers'])]
#[ApiFilter(PropertyFilter::class)]
#[ApiFilter(QuestionSearchFilter::class)]
#[ORM\Entity(repositoryClass: QuestionRepository::class)]
#[ORM\EntityListeners([SetOwnerListener::class])]
class Question
{
    // use it for the created and updated fields
    //use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['question:read', 'question:write', 'userAPI:read'])]
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 50, maxMessage: 'The question name is too long.')]
    private ?string $title = null;

    #[Groups(['question:read'])]
    #[ORM\Column(length: 100)]
    #[Gedmo\Slug(fields: ['title'])]
    private ?string $slug = null;

    #[Groups(['question:read', 'userAPI:read'])]
    #[SerializedName('description')]
    #[ORM\Column(type: Types::TEXT)]
    //#[Assert\NotBlank]
    //#[Assert\Length(min: 2, max: 255, maxMessage: 'The question description is too long.')]
    private ?string $question = null;

    #[Groups(['question:read', 'question:write'])]
    #[Assert\NotBlank]
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $askedAt = null;

    #[Groups(['question:write'])]
    #[ORM\Column]
    private int $votes = 0;

    #[Groups(['question:read', 'admin:write'])]
    #[ORM\Column]
    private ?bool $isPublished = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Gedmo\Timestampable(on: 'create')]
    private $createdAt;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Gedmo\Timestampable(on: 'update')]
    private $updatedAt;

    #[Groups(['question:read'])]
    #[ORM\OneToMany(mappedBy: 'question', targetEntity: Answer::class, fetch: 'EXTRA_LAZY'), OrderBy(['createdAt' => 'DESC'])]
    private Collection $answers;

    #[Groups(['question:read', 'question:write'])]
    #[Assert\NotBlank]
    #[ORM\ManyToMany(targetEntity: Tag::class, fetch: 'EXTRA_LAZY', inversedBy: 'questions')]
    private Collection $tags;

    #[Groups(['question:read'])]
    #[ORM\ManyToOne(inversedBy: 'questions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    #[Groups(['question:write'])]
    #[SerializedName('description')]
    public function setTextQuestion(string $question): self
    {
        $this->question = nl2br($question);

        return $this;
    }

    #[Groups(['question:read'])]
    public function getShortQuestion(): ?string
    {
        //strip_tags
        if (strlen($this->question) < 40) {
            return $this->question;
        }

        return substr($this->question, 0, 40) . '...';
    }

    public function getAskedAt(): ?\DateTimeInterface
    {
        return $this->askedAt;
    }

    public function setAskedAt(?\DateTimeInterface $askedAt): self
    {
        $this->askedAt = $askedAt;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    #[Groups(['question:read'])]
    #[SerializedName('votes')]
    public function getVotesString(): string
    {
        $prefix = $this->votes > 0 ? '+' : '-';

        return sprintf('%s%d', $prefix, abs($this->getVotes()));
    }

    public function upVote(): self
    {
        $this->votes++;

        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    #[Groups(['question:read'])]
    public function getCreatedAtAgo(): string
    {
        return Carbon::instance($this->getCreatedAt())->diffForHumans();
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    #[Groups(['question:read'])]
    public function getUpdatedAtAgo(): string
    {
        return Carbon::instance($this->getUpdatedAt())->diffForHumans();
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    /*public function getApprovedAnswers(): Collection
    {
        //return $this->answers->filter(function (Answer $answer) {
          //  return $answer->isApproved();
        //});

        return $this->answers->matching(AnswerRepository::createApprovedCriteria());
    }*/

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Controller/QuestionController.php
<?php

namespace App\Controller;

use App\Entity\Question;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Doctrine\ORM\QueryAdapter;

class QuestionController extends AbstractController
{
    #[Route('/questions/{page<\d+>}', name: 'app_question')]
    public function index(QuestionRepository $questionRepository, Request $request, int $page = 1): Response
    {
        //$questions = $questionRepository->findAllAskedOrderedByNewest();
        $queryBuilder = $questionRepository->createAskedOrderByNewestQueryBuilder();

        $pagerfanta = new Pagerfanta(
            new QueryAdapter($queryBuilder)
        );
        $pagerfanta->setMaxPerPage(5);
        $pagerfanta->setCurrentPage($page);
        //$pagerfanta->setCurrentPage($request->query->getInt('page', 1));
        //dd($questions);

        return $this->render('question/index.html.twig', [
            'pager' => $pagerfanta,
            //'questions' => $questions,
        ]);
    }

    //Automatic Controller Queries: Param Converter
    #[Route('/questions/{slug}', name: 'app_question_show')]
    public function show(Question $question): Response
    {
        return $this->render('question/show.html.twig', [
            'question' => $question,
        ]);
    }


    #[Route('/questions/edit/{slug}', name: 'app_question_edit')]
    public function edit(Question $question): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');
        // $this->denyAccessUnlessGranted('EDIT', $question);

        if ($question->getOwner() !== $this->getUser()) {
            throw $this->createAccessDeniedException('You can not edit this question, beqause you are not the owner.');
        }

        return $this->render('question/edit.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/questions/{slug}/vote', name: 'app_question_vote', methods: ['POST'])]
    public function questionVoteCount(Question $question, Request $request, EntityManagerInterface $entityManager)
    {
        $direction = $request->request->get('direction');

        if ($direction === 'up') {
            $question->upVote();
        } elseif ($direction === 'down') {
            $question->downVote();
        }

        //dd($question, $request->request->all());

        $entityManager->flush();

        return $this->redirectToRoute('app_question_show', [
            'slug' => $question->getSlug(),
        ]);
    }
}

templates/question/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Edit Qustion:
	{{ question.title }}
{% endblock %}

{% block body %}
	<div class="container mx-auto my-10">

		<div class="flex justify-center">
			<div class="flex flex-col md:flex-row w-xl rounded-lg bg-white shadow-lg">
				<img class=" w-full h-96 md:h-auto object-cover md:w-48 rounded-t-lg md:rounded-none md:rounded-l-lg" src="{{ question.owner.getAvatarURL }}" alt=""/>
				<div class="p-6 flex flex-col justify-start">
					<h5 class="text-gray-900 text-xl font-medium mb-2">Edit Qustion</h5>
					<p class="text-gray-700 text-base mb-4">
						<blockquote>{{ question.question }}</blockquote>
					</p>
					<br>
					<p class="text-gray-600 text-xs">Last updated
						{{ question.updatedAt|ago }}</p>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

templates/question/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello QuestionController!
{% endblock %}

{% block body %}
	<div>
		<div class="bg-white w-screen flex items-center justify-center">
			<div class="mx-auto w-full bg-blue-600 px-5 py-10">
				<div class="grid gap-5 md:grid-cols-2 md:gap-10 lg:gap-20">
					<div class="flex justify-center md:justify-end">
						<img class="w-full max-w-sm" src="https://ouch-cdn2.icons8.com/sKnF2PmYhkmP28DzIm6KqWSknT03UVWjg3FLlGYIOp4/rs:fit:684:456/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9zdmcvOTI3/L2U4OWQ2NmZiLTg0/NzEtNDc3NS1hNTA0/LTMwNWRiYmJkNzg0/MC5zdmc.png" alt="Marketing newsletter via computer Illustration in PNG, SVG"/>
					</div>
					<div class="flex items-center">
						<div class="mx-auto md:mx-0">
							<h3 class="text-4xl font-bold text-white">Your Qustions Answered</h3>
							<p class="mt-2 max-w-[20rem] text-lg text-white/80">Join our weekly digest. You'll also receive some of our best posts today.</p>
							<div class="grid grid-cols-2 gap-10">
								<div class="mt-4 flex flex-col">
									<input type="search" name="search" id="search" placeholder="Enter your search" class="w-full rounded border border-white/50 bg-transparent px-3 py-2 text-white placeholder:text-white/50 md:max-w-[18rem]"/>
									<button type="submit" class="mt-4 w-full max-w-[14rem] rounded bg-white/30 hover:bg-white/50 hover:shadow px-14 py-2 text-center text-white">Submit</button>
								</div>
								<div class="">
									<button type=" submit" class=" mt-4 w-full max-w-[14rem] rounded bg-white/30 hover:bg-white/50 hover:shadow px-14 py-2 text-center text-white">Ask a Question</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div data-controller="hello" class="mx-10">
		<input data-hello-target="name" type="text">

		<button data-action="click->hello#greet">
			Greet
		</button>
		<span data-hello-target="output"></span>
	</div>

	<div
		class="container mx-auto my-10">
		<!-- component -->
		{% for question in pager %}
			<div class='flex items-center justify-center my-5'>
				<div class="rounded-xl border p-5 shadow-md w-9/12 bg-white">
					<div class="flex w-full items-center justify-between border-b pb-3">
						<div
							class="flex items-center space-x-3">
							<!--<div class="h-8 w-8 rounded-full bg-slate-400 bg-[url('https://i.pravatar.cc/32')]"></div>-->
							<div class="h-8 w-8 rounded-full bg-slate-400">
								<img src="{{ question.owner.getAvatarURL }}" alt="">
							</div>
							<div class="text-lg font-bold text-slate-700">{{ question.owner.getDisplayName }}</div>
						</div>
						<div class="flex items-center space-x-8">
							{% for  tag in question.tags %}
								<button class="rounded-2xl border bg-neutral-100 px-3 py-1 text-xs font-semibold">{{ tag.name }}</button>
							{% endfor %}
							<div class="text-xs text-neutral-500">
								{% if question.askedAt %}
									Asked
									{{ question.askedAt|ago }}
								{% else %}
									(unpublished)
								{% endif %}
							</div>
						</div>
					</div>

					<div class="mt-4 mb-6">
						<div class="mb-3 text-xl font-bold">
							<a class="no-underline hover:underline" href="{{ path('app_question_show', { slug: question.slug }) }}">
								{{ question.title }}
							</a>
						</div>
						<div class="text-sm text-neutral-600">{{ question.question|parse_markdown  }}</div>
					</div>

					<div>
						<div class="flex items-center justify-between text-slate-500">
							<div class="flex space-x-4 md:space-x-8">
								<div class="flex cursor-pointer items-center transition hover:text-slate-600">
									<svg xmlns="http://www.w3.org/2000/svg" class="mr-1.5 h-5 w-5" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"/>
									</svg>
									<span>{{ question.Answers|length }}</span>
								</div>
								<div class="flex cursor-pointer items-center transition hover:text-slate-600">
									<svg xmlns="http://www.w3.org/2000/svg" class="mr-1.5 h-5 w-5" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"/>
									</svg>
									<span>{{ question.votesString }}</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
		{{ pagerfanta(pager) }}
	</div>
{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Question:
	{{ question.title }}
{% endblock %}

{% block body %}
	<!-- component -->
	<div class='flex items-center justify-center my-10'>
		<div class="rounded-xl border p-5 shadow-md w-9/12 bg-white">
			<div class="flex w-full items-center justify-between border-b pb-3">
				<div class="flex items-center space-x-3">
					<div class="h-8 w-8 rounded-full bg-slate-400">
						<img src="{{ question.owner.getAvatarURL }}" alt="">
					</div>
					<div class="text-lg font-bold text-slate-700">{{ question.owner.getDisplayName }}</div>
					<a href="{{ path('app_question_edit', { slug: question.slug }) }}">
						<i class="fas fa-edit"></i>
					</a>
				</div>
				<div class="flex items-center space-x-8">
					<button class="rounded-2xl border bg-neutral-100 px-3 py-1 text-xs font-semibold">Category</button>
					<div class="text-xs text-neutral-500">
						{% if question.createdAt %}
							Asked
							{{ question.createdAt|ago }}
						{% else %}
							(unpublished)
						{% endif %}
					</div>
				</div>
			</div>

			<div class="mt-4 mb-6">
				<div class="mb-3 text-xl font-bold">{{ question.title }}</div>
				<div class="text-sm text-neutral-600">{{ question.question|parse_markdown }}</div>
			</div>

			<div>
				<div class="flex items-center justify-between border-b pb-3 text-slate-500">
					<div class="flex space-x-4 md:space-x-8">
						<div class="flex cursor-pointer items-center transition hover:text-slate-600">
							<svg xmlns="http://www.w3.org/2000/svg" class="mr-1.5 h-5 w-5" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="2">
								<path stroke-linecap="round" stroke-linejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"/>
							</svg>
							<span>{{ question.Answers|length }}</span>
						</div>
						<div class="flex cursor-pointer items-center transition hover:text-slate-600">
							<svg xmlns="http://www.w3.org/2000/svg" class="mr-1.5 h-5 w-5" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="2">
								<path stroke-linecap="round" stroke-linejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"/>
							</svg>
							<span>{{ question.votesString }}</span>
						</div>

						{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
							<form action="{{ path('app_question_vote', { slug: question.slug }) }}" method="POST">
								<div class="vote-arrows vote-arrows-alt flex-fill pt-2 text-dark" style="min-width: 90px;">
									<button class="vote-up btn btn-link" name="direction" value="up">
										<i class="far fa-arrow-alt-circle-up"></i>
									</button>
									<button class="vote-down btn btn-link" name="direction" value="down">
										<i class="far fa-arrow-alt-circle-down"></i>
									</button>
									<span>{{ question.votesString }}</span>
								</div>
							</form>
						{% endif %}

						<div class="">
							<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit an Answer</button>
						</div>
					</div>
				</div>
			</div>

			<div class="flex w-full items-center justify-between">
				<div>
					<ul class="list-unstyled">
						{% for answer in question.Answers %}
							{{ include('answer/question_answers.html.twig') }}
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>
{% endblock %}